eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
server:
  port: 8087

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhengkb/mystudy
#          uri: https://git.oschina.net/chrywhy/test
#          searchPaths: spring-cloud/helloworldConfig
  application:
    name: config-server